/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SummariesModel,
} from '../models';
import {
    SummariesModelFromJSON,
    SummariesModelToJSON,
} from '../models';

export interface GetWeekSummaryRequest {
    week: number;
}

/**
 * 
 */
export class SummariesApi extends runtime.BaseAPI {

    /**
     */
    async getSeasonSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SummariesModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/summaries/season`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SummariesModelFromJSON(jsonValue));
    }

    /**
     */
    async getSeasonSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SummariesModel> {
        const response = await this.getSeasonSummaryRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getWeekSummaryRaw(requestParameters: GetWeekSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SummariesModel>> {
        if (requestParameters.week === null || requestParameters.week === undefined) {
            throw new runtime.RequiredError('week','Required parameter requestParameters.week was null or undefined when calling getWeekSummary.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/summaries/week/{week}`.replace(`{${"week"}}`, encodeURIComponent(String(requestParameters.week))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SummariesModelFromJSON(jsonValue));
    }

    /**
     */
    async getWeekSummary(requestParameters: GetWeekSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SummariesModel> {
        const response = await this.getWeekSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
