/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthData } from './AuthData';
import {
    AuthDataFromJSON,
    AuthDataFromJSONTyped,
    AuthDataToJSON,
} from './AuthData';

/**
 * 
 * @export
 * @interface AuthResult
 */
export interface AuthResult {
    /**
     * 
     * @type {boolean}
     * @memberof AuthResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    message?: string;
    /**
     * 
     * @type {AuthData}
     * @memberof AuthResult
     */
    data?: AuthData;
}

/**
 * Check if a given object implements the AuthResult interface.
 */
export function instanceOfAuthResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthResultFromJSON(json: any): AuthResult {
    return AuthResultFromJSONTyped(json, false);
}

export function AuthResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : AuthDataFromJSON(json['data']),
    };
}

export function AuthResultToJSON(value?: AuthResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': AuthDataToJSON(value.data),
    };
}

