/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthSchema } from './AuthSchema';
import {
    AuthSchemaFromJSON,
    AuthSchemaFromJSONTyped,
    AuthSchemaToJSON,
} from './AuthSchema';

/**
 * 
 * @export
 * @interface AuthModel
 */
export interface AuthModel {
    /**
     * 
     * @type {boolean}
     * @memberof AuthModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthModel
     */
    message?: string;
    /**
     * 
     * @type {AuthSchema}
     * @memberof AuthModel
     */
    data?: AuthSchema;
}

/**
 * Check if a given object implements the AuthModel interface.
 */
export function instanceOfAuthModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthModelFromJSON(json: any): AuthModel {
    return AuthModelFromJSONTyped(json, false);
}

export function AuthModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : AuthSchemaFromJSON(json['data']),
    };
}

export function AuthModelToJSON(value?: AuthModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': AuthSchemaToJSON(value.data),
    };
}

