/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSchema
 */
export interface AuthSchema {
    /**
     * 
     * @type {string}
     * @memberof AuthSchema
     */
    token?: string;
}

/**
 * Check if a given object implements the AuthSchema interface.
 */
export function instanceOfAuthSchema(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthSchemaFromJSON(json: any): AuthSchema {
    return AuthSchemaFromJSONTyped(json, false);
}

export function AuthSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function AuthSchemaToJSON(value?: AuthSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

