/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntrySchema
 */
export interface EntrySchema {
    /**
     * 
     * @type {number}
     * @memberof EntrySchema
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EntrySchema
     */
    entry?: string;
}

/**
 * Check if a given object implements the EntrySchema interface.
 */
export function instanceOfEntrySchema(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EntrySchemaFromJSON(json: any): EntrySchema {
    return EntrySchemaFromJSONTyped(json, false);
}

export function EntrySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntrySchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'entry': !exists(json, 'entry') ? undefined : json['entry'],
    };
}

export function EntrySchemaToJSON(value?: EntrySchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'entry': value.entry,
    };
}

