/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameSchema } from './GameSchema';
import {
    GameSchemaFromJSON,
    GameSchemaFromJSONTyped,
    GameSchemaToJSON,
} from './GameSchema';

/**
 * 
 * @export
 * @interface GameModel
 */
export interface GameModel {
    /**
     * 
     * @type {boolean}
     * @memberof GameModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameModel
     */
    message?: string;
    /**
     * 
     * @type {GameSchema}
     * @memberof GameModel
     */
    data?: GameSchema;
}

/**
 * Check if a given object implements the GameModel interface.
 */
export function instanceOfGameModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameModelFromJSON(json: any): GameModel {
    return GameModelFromJSONTyped(json, false);
}

export function GameModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : GameSchemaFromJSON(json['data']),
    };
}

export function GameModelToJSON(value?: GameModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': GameSchemaToJSON(value.data),
    };
}

