/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamePick
 */
export interface GamePick {
    /**
     * 
     * @type {number}
     * @memberof GamePick
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof GamePick
     */
    gameId?: number;
    /**
     * 
     * @type {string}
     * @memberof GamePick
     */
    pick?: string;
    /**
     * 
     * @type {number}
     * @memberof GamePick
     */
    amount?: number;
}

/**
 * Check if a given object implements the GamePick interface.
 */
export function instanceOfGamePick(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GamePickFromJSON(json: any): GamePick {
    return GamePickFromJSONTyped(json, false);
}

export function GamePickFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamePick {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
        'gameId': !exists(json, 'game_id') ? undefined : json['game_id'],
        'pick': !exists(json, 'pick') ? undefined : json['pick'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
    };
}

export function GamePickToJSON(value?: GamePick | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
        'game_id': value.gameId,
        'pick': value.pick,
        'amount': value.amount,
    };
}

