/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GamePickData } from './GamePickData';
import {
    GamePickDataFromJSON,
    GamePickDataFromJSONTyped,
    GamePickDataToJSON,
} from './GamePickData';

/**
 * 
 * @export
 * @interface GamePickModel
 */
export interface GamePickModel {
    /**
     * 
     * @type {boolean}
     * @memberof GamePickModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GamePickModel
     */
    message?: string;
    /**
     * 
     * @type {GamePickData}
     * @memberof GamePickModel
     */
    data?: GamePickData;
}

/**
 * Check if a given object implements the GamePickModel interface.
 */
export function instanceOfGamePickModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GamePickModelFromJSON(json: any): GamePickModel {
    return GamePickModelFromJSONTyped(json, false);
}

export function GamePickModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamePickModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : GamePickDataFromJSON(json['data']),
    };
}

export function GamePickModelToJSON(value?: GamePickModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': GamePickDataToJSON(value.data),
    };
}

