/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Game
 */
export interface Game {
    /**
     * 
     * @type {number}
     * @memberof Game
     */
    week?: number;
    /**
     * 
     * @type {string}
     * @memberof Game
     */
    result?: GameResultEnum;
    /**
     * 
     * @type {number}
     * @memberof Game
     */
    homeTeamId?: number;
    /**
     * 
     * @type {number}
     * @memberof Game
     */
    awayTeamId?: number;
}


/**
 * @export
 */
export const GameResultEnum = {
    _1: '1',
    _2: '2',
    _3: '3',
    _4: '4'
} as const;
export type GameResultEnum = typeof GameResultEnum[keyof typeof GameResultEnum];


/**
 * Check if a given object implements the Game interface.
 */
export function instanceOfGame(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameFromJSON(json: any): Game {
    return GameFromJSONTyped(json, false);
}

export function GameFromJSONTyped(json: any, ignoreDiscriminator: boolean): Game {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'week': !exists(json, 'week') ? undefined : json['week'],
        'result': !exists(json, 'result') ? undefined : json['result'],
        'homeTeamId': !exists(json, 'home_team_id') ? undefined : json['home_team_id'],
        'awayTeamId': !exists(json, 'away_team_id') ? undefined : json['away_team_id'],
    };
}

export function GameToJSON(value?: Game | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'week': value.week,
        'result': value.result,
        'home_team_id': value.homeTeamId,
        'away_team_id': value.awayTeamId,
    };
}

