/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MessageSchema } from './MessageSchema';
import {
    MessageSchemaFromJSON,
    MessageSchemaFromJSONTyped,
    MessageSchemaToJSON,
} from './MessageSchema';

/**
 * 
 * @export
 * @interface MessageModel
 */
export interface MessageModel {
    /**
     * 
     * @type {boolean}
     * @memberof MessageModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MessageModel
     */
    message?: string;
    /**
     * 
     * @type {Array<MessageSchema>}
     * @memberof MessageModel
     */
    data?: Array<MessageSchema>;
}

/**
 * Check if a given object implements the MessageModel interface.
 */
export function instanceOfMessageModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MessageModelFromJSON(json: any): MessageModel {
    return MessageModelFromJSONTyped(json, false);
}

export function MessageModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(MessageSchemaFromJSON)),
    };
}

export function MessageModelToJSON(value?: MessageModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(MessageSchemaToJSON)),
    };
}

