/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VersionSchema } from './VersionSchema';
import {
    VersionSchemaFromJSON,
    VersionSchemaFromJSONTyped,
    VersionSchemaToJSON,
} from './VersionSchema';

/**
 * 
 * @export
 * @interface MiscSchema
 */
export interface MiscSchema {
    /**
     * 
     * @type {boolean}
     * @memberof MiscSchema
     */
    started?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MiscSchema
     */
    currentWeek?: number;
    /**
     * 
     * @type {VersionSchema}
     * @memberof MiscSchema
     */
    versions?: VersionSchema;
}

/**
 * Check if a given object implements the MiscSchema interface.
 */
export function instanceOfMiscSchema(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MiscSchemaFromJSON(json: any): MiscSchema {
    return MiscSchemaFromJSONTyped(json, false);
}

export function MiscSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MiscSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'started': !exists(json, 'started') ? undefined : json['started'],
        'currentWeek': !exists(json, 'current_week') ? undefined : json['current_week'],
        'versions': !exists(json, 'versions') ? undefined : VersionSchemaFromJSON(json['versions']),
    };
}

export function MiscSchemaToJSON(value?: MiscSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'started': value.started,
        'current_week': value.currentWeek,
        'versions': VersionSchemaToJSON(value.versions),
    };
}

