/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserSchema } from './UserSchema';
import {
    UserSchemaFromJSON,
    UserSchemaFromJSONTyped,
    UserSchemaToJSON,
} from './UserSchema';

/**
 * 
 * @export
 * @interface PickStatusSchema
 */
export interface PickStatusSchema {
    /**
     * 
     * @type {UserSchema}
     * @memberof PickStatusSchema
     */
    user?: UserSchema;
    /**
     * 
     * @type {number}
     * @memberof PickStatusSchema
     */
    status?: number;
}

/**
 * Check if a given object implements the PickStatusSchema interface.
 */
export function instanceOfPickStatusSchema(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PickStatusSchemaFromJSON(json: any): PickStatusSchema {
    return PickStatusSchemaFromJSONTyped(json, false);
}

export function PickStatusSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickStatusSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserSchemaFromJSON(json['user']),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function PickStatusSchemaToJSON(value?: PickStatusSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserSchemaToJSON(value.user),
        'status': value.status,
    };
}

