/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PickStatusSchema } from './PickStatusSchema';
import {
    PickStatusSchemaFromJSON,
    PickStatusSchemaFromJSONTyped,
    PickStatusSchemaToJSON,
} from './PickStatusSchema';

/**
 * 
 * @export
 * @interface PickStatusesModel
 */
export interface PickStatusesModel {
    /**
     * 
     * @type {boolean}
     * @memberof PickStatusesModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PickStatusesModel
     */
    message?: string;
    /**
     * 
     * @type {Array<PickStatusSchema>}
     * @memberof PickStatusesModel
     */
    data?: Array<PickStatusSchema>;
}

/**
 * Check if a given object implements the PickStatusesModel interface.
 */
export function instanceOfPickStatusesModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PickStatusesModelFromJSON(json: any): PickStatusesModel {
    return PickStatusesModelFromJSONTyped(json, false);
}

export function PickStatusesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickStatusesModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(PickStatusSchemaFromJSON)),
    };
}

export function PickStatusesModelToJSON(value?: PickStatusesModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(PickStatusSchemaToJSON)),
    };
}

