/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadIds
 */
export interface ReadIds {
    /**
     * 
     * @type {Array<number>}
     * @memberof ReadIds
     */
    ids?: Array<number>;
}

/**
 * Check if a given object implements the ReadIds interface.
 */
export function instanceOfReadIds(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadIdsFromJSON(json: any): ReadIds {
    return ReadIdsFromJSONTyped(json, false);
}

export function ReadIdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadIds {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ids': !exists(json, 'ids') ? undefined : json['ids'],
    };
}

export function ReadIdsToJSON(value?: ReadIds | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ids': value.ids,
    };
}

