/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadIds } from './ReadIds';
import {
    ReadIdsFromJSON,
    ReadIdsFromJSONTyped,
    ReadIdsToJSON,
} from './ReadIds';

/**
 * 
 * @export
 * @interface ReadIdsModel
 */
export interface ReadIdsModel {
    /**
     * 
     * @type {boolean}
     * @memberof ReadIdsModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReadIdsModel
     */
    message?: string;
    /**
     * 
     * @type {ReadIds}
     * @memberof ReadIdsModel
     */
    data?: ReadIds;
}

/**
 * Check if a given object implements the ReadIdsModel interface.
 */
export function instanceOfReadIdsModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadIdsModelFromJSON(json: any): ReadIdsModel {
    return ReadIdsModelFromJSONTyped(json, false);
}

export function ReadIdsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadIdsModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ReadIdsFromJSON(json['data']),
    };
}

export function ReadIdsModelToJSON(value?: ReadIdsModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': ReadIdsToJSON(value.data),
    };
}

