/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReleaseNotesSchema } from './ReleaseNotesSchema';
import {
    ReleaseNotesSchemaFromJSON,
    ReleaseNotesSchemaFromJSONTyped,
    ReleaseNotesSchemaToJSON,
} from './ReleaseNotesSchema';

/**
 * 
 * @export
 * @interface ReleaseNotesModel
 */
export interface ReleaseNotesModel {
    /**
     * 
     * @type {boolean}
     * @memberof ReleaseNotesModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReleaseNotesModel
     */
    message?: string;
    /**
     * 
     * @type {ReleaseNotesSchema}
     * @memberof ReleaseNotesModel
     */
    data?: ReleaseNotesSchema;
}

/**
 * Check if a given object implements the ReleaseNotesModel interface.
 */
export function instanceOfReleaseNotesModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReleaseNotesModelFromJSON(json: any): ReleaseNotesModel {
    return ReleaseNotesModelFromJSONTyped(json, false);
}

export function ReleaseNotesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseNotesModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ReleaseNotesSchemaFromJSON(json['data']),
    };
}

export function ReleaseNotesModelToJSON(value?: ReleaseNotesModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': ReleaseNotesSchemaToJSON(value.data),
    };
}

