/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SummarySchema } from './SummarySchema';
import {
    SummarySchemaFromJSON,
    SummarySchemaFromJSONTyped,
    SummarySchemaToJSON,
} from './SummarySchema';

/**
 * 
 * @export
 * @interface SummariesModel
 */
export interface SummariesModel {
    /**
     * 
     * @type {boolean}
     * @memberof SummariesModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SummariesModel
     */
    message?: string;
    /**
     * 
     * @type {Array<SummarySchema>}
     * @memberof SummariesModel
     */
    data?: Array<SummarySchema>;
}

/**
 * Check if a given object implements the SummariesModel interface.
 */
export function instanceOfSummariesModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SummariesModelFromJSON(json: any): SummariesModel {
    return SummariesModelFromJSONTyped(json, false);
}

export function SummariesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummariesModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(SummarySchemaFromJSON)),
    };
}

export function SummariesModelToJSON(value?: SummariesModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(SummarySchemaToJSON)),
    };
}

