/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamSchema
 */
export interface TeamSchema {
    /**
     * 
     * @type {number}
     * @memberof TeamSchema
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamSchema
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamSchema
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamSchema
     */
    abbreviation?: string;
}

/**
 * Check if a given object implements the TeamSchema interface.
 */
export function instanceOfTeamSchema(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamSchemaFromJSON(json: any): TeamSchema {
    return TeamSchemaFromJSONTyped(json, false);
}

export function TeamSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'abbreviation': !exists(json, 'abbreviation') ? undefined : json['abbreviation'],
    };
}

export function TeamSchemaToJSON(value?: TeamSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'city': value.city,
        'abbreviation': value.abbreviation,
    };
}

