/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    abbreviation?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    conference?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    division?: string;
}

/**
 * Check if a given object implements the Team interface.
 */
export function instanceOfTeam(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TeamFromJSON(json: any): Team {
    return TeamFromJSONTyped(json, false);
}

export function TeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Team {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'abbreviation': !exists(json, 'abbreviation') ? undefined : json['abbreviation'],
        'conference': !exists(json, 'conference') ? undefined : json['conference'],
        'division': !exists(json, 'division') ? undefined : json['division'],
    };
}

export function TeamToJSON(value?: Team | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'city': value.city,
        'abbreviation': value.abbreviation,
        'conference': value.conference,
        'division': value.division,
    };
}

