/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPassword
 */
export interface UserPassword {
    /**
     * 
     * @type {string}
     * @memberof UserPassword
     */
    password?: string;
}

/**
 * Check if a given object implements the UserPassword interface.
 */
export function instanceOfUserPassword(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserPasswordFromJSON(json: any): UserPassword {
    return UserPasswordFromJSONTyped(json, false);
}

export function UserPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPassword {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function UserPasswordToJSON(value?: UserPassword | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
    };
}

