/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserData } from './UserData';
import {
    UserDataFromJSON,
    UserDataFromJSONTyped,
    UserDataToJSON,
} from './UserData';

/**
 * 
 * @export
 * @interface UserListModel
 */
export interface UserListModel {
    /**
     * 
     * @type {boolean}
     * @memberof UserListModel
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserListModel
     */
    message?: string;
    /**
     * 
     * @type {Array<UserData>}
     * @memberof UserListModel
     */
    data?: Array<UserData>;
}

/**
 * Check if a given object implements the UserListModel interface.
 */
export function instanceOfUserListModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserListModelFromJSON(json: any): UserListModel {
    return UserListModelFromJSONTyped(json, false);
}

export function UserListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(UserDataFromJSON)),
    };
}

export function UserListModelToJSON(value?: UserListModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(UserDataToJSON)),
    };
}

