/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionSchema
 */
export interface VersionSchema {
    /**
     * 
     * @type {number}
     * @memberof VersionSchema
     */
    ios?: number;
    /**
     * 
     * @type {number}
     * @memberof VersionSchema
     */
    android?: number;
    /**
     * 
     * @type {number}
     * @memberof VersionSchema
     */
    server?: number;
}

/**
 * Check if a given object implements the VersionSchema interface.
 */
export function instanceOfVersionSchema(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VersionSchemaFromJSON(json: any): VersionSchema {
    return VersionSchemaFromJSONTyped(json, false);
}

export function VersionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ios': !exists(json, 'ios') ? undefined : json['ios'],
        'android': !exists(json, 'android') ? undefined : json['android'],
        'server': !exists(json, 'server') ? undefined : json['server'],
    };
}

export function VersionSchemaToJSON(value?: VersionSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ios': value.ios,
        'android': value.android,
        'server': value.server,
    };
}

