/* tslint:disable */
/* eslint-disable */
/**
 * Pick Em League Swagger
 * Welcome to the Swagger UI documentation site!
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import type { UserSchema } from './UserSchema';
import {
  UserSchemaFromJSON,
  UserSchemaToJSON
} from './UserSchema';

/**
 * 
 * @export
 * @interface SummarySchema
 */
export interface SummarySchema {
    /**
     * 
     * @type {UserSchema}
     * @memberof SummarySchema
     */
    user?: UserSchema;
    /**
     * 
     * @type {number}
     * @memberof SummarySchema
     */
    score?: number;
    /**
     * 
     * @type {number}
     * @memberof SummarySchema
     */
    correctPicks?: number;
}

/**
 * Check if a given object implements the SummarySchema interface.
 */
export function instanceOfSummarySchema(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SummarySchemaFromJSON(json: any): SummarySchema {
    return SummarySchemaFromJSONTyped(json, false);
}

export function SummarySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummarySchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserSchemaFromJSON(json['user']),
        'score': !exists(json, 'score') ? undefined : json['score'],
        'correctPicks': !exists(json, 'correct_picks') ? undefined : json['correct_picks'],
    };
}

export function SummarySchemaToJSON(value?: SummarySchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserSchemaToJSON(value.user),
        'score': value.score,
        'correct_picks': value.correctPicks,
    };
}

